### PR TITLE
feat(angular): handle params

### PR DESCRIPTION
**Pull request by lekhmanrus**
Handle Angular `params` to form the correct URL.

### CODE REVIEW

**Comment by farfromrefug** [comment]
@lekhmanrus thanks it is now released

**Comment by lekhmanrus** [comment]
@farfromrefug thank you!

**Comment by lekhmanrus** [comment]
Hey @@farfromrefug,
For some reason, **v4.1.3** doesn't contain an angular folder. Maybe, has something changed in the build process?
See - **v4.1.3** contains only [28 files](https://www.npmjs.com/package/@nativescript-community/https/v/4.1.3?activeTab=code), and **v4.1.2** contains [42](https://www.npmjs.com/package/@nativescript-community/https/v/4.1.2?activeTab=code).

**Comment by farfromrefug** [comment]
@lekhmanrus indeed:
there is a build error:
```
../../src/https/angular/ns-http-xhr-backend.ts:2:80 - error TS2459: Module '"@angular/common/http"' declares 'XhrFactory' locally, but it is not exported.

2 import { HttpErrorResponse, HttpEvent, HttpHeaders, HttpRequest, HttpResponse, XhrFactory } from '@angular/common/http';
```
any idea?
and there is another error. My build process does not stop on error...

**Comment by lekhmanrus** [comment]
@farfromrefug,
Yep, in Angular v16 `XhrFactory` export from `@angular/common/http` has been removed. I'll fix that shortly.

**Pull request merged**
