### PR TITLE
fix: angular build

### PR DESCRIPTION
**Pull request by lekhmanrus**
Fixed angular build to use `ng-packagr` instead of `tsc`.

### CODE REVIEW

**Comment by farfromrefug** [comment]
@lekhmanrus thanks. Globally ok with it. Could you  revert the change to packages/https/package.json ? The changes you made to the scripts are no good. All the rest seems good to me.
Sorry for.missing all this

**Comment by lekhmanrus** [comment]
Hi @farfromrefug,
I'm not 100% sure what is workflow here, but just wanted to confirm - when I reset the `packages/https/package.json` file changes and run the `yarn build.all` -  angular folder at `/packages/` won't generate - is it expected behaviour? Or maybe something else should be changed instead?

Also, I'll commit formatting changes soon, since I've noticed you used 4 spaces indentation here. And other formatting issues I had (based on your prettier settings)

**Comment by farfromrefug** [comment]
Npm build.all is supposed to call npm build and npm build.angular.
If you run npm build.angular at top level does it build angular ? I remember it did here but with tsc and not with ng packgr. I forgot the exclusion in tsconfig.

**Comment by lekhmanrus** [comment]
I tried `yarn build.all` at the root level and for some reason it does not build angular - that's why I added those changes before (now reverted as you asked). But if it works on your side - that's fine for me - maybe something is wrong with my setup. 🙂

**Comment by farfromrefug** [comment]
@lekhmanrus maybe it is nord only you. If you can revert the change to package.json then I ll merge and ensure it works correctly

**Comment by lekhmanrus** [comment]
Hi @farfromrefug, it was reverted yesterday. Do you want me to do anything else with that?

**Comment by farfromrefug** [comment]
#@lekhmanrus sorry I was expecting a new commit. I will test

**Comment by lekhmanrus** [comment]
Hey @farfromrefug, did you have a chance to review these changes? 🙂

**Comment by farfromrefug** [comment]
@lekhmanrus my bad i completely forgot!

**Pull request merged**
