### PR TITLE
Content on android and IOS are different 

### PR DESCRIPTION
**Pull request by kefahB**
Hi @EddyVerbruggen ,

I've just migrated my projects to NS7 and I realized that the response on android and IOS are different ! 

For example if the server return status different then `200` for example `301`, android will return content as `string` but IOS will trigger the `AFFailure` without content on the response !!

I think since Nativescript it is a Javascript world, the response should be identique on both platforms, and especially response.content should return a json object.

Please give it a try.

### CODE REVIEW

**Comment by kefahB** [comment]
Hi @farfromrefug,

What do you think about this ?

**Comment by farfromrefug** [comment]
@kefahB sorry missed this. Can you fix the conflicts?
I ll trust you that it works as i always use `useLegacy`

**Comment by kefahB** [comment]
@farfromrefug conflict was resolved .. please give it a try before merging.

Thanks

**Comment by kefahB** [comment]
@farfromrefug did you try ? need to push a new release before 15 novembre ;)

**Comment by farfromrefug** [comment]
@kefahB how can i test this? Please create a way to test this in the demo or something. I dont really have much time to test this, especially as i dont use it.
Thanks

**Comment by farfromrefug** [comment]
@kefahB it should be integrated in latest version. thanks

**Pull request closed without merging**
