### PR TITLE
Malformed data due to data.classe() return undefined

### PR DESCRIPTION
**Pull request by kefahB**
Hi @EddyVerbruggen ,

I fix the issue with the malformed data related with #56  .. the issue is fixed by replacing `data.class().name` by `data instanceof NSArray`

### CODE REVIEW

**Comment by kefahB** [comment]
@EddyVerbruggen , I pushed another commit related with #54

**Comment by kefahB** [comment]
Hi @EddyVerbruggen 

Can you review this PR please. thanks

**Comment by EddyVerbruggen** [comment]
@kefahB I'd love to, but it has been closed. Was that on purpose?

**Comment by kefahB** [comment]
Hi @EddyVerbruggen 

I had other issue on android .. and I decided to close this and create one more complete [here](https://github.com/EddyVerbruggen/nativescript-https/pull/60)

**Pull request closed without merging**
