### PR TITLE
Bump AFNetworking and add opt-in support for large HTTP responses on Android

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
Hi!

Thanks for maintaining this cool plugin, I've been using it in a few projects myself. 👌

I ran into a few issues that I wanted to share, after having these in my fork for a while. I hope you'll accept this PR and release a new version to npm.

#### Changes:
- Bump AFNetworking to the latest version. This fixes a security vulnerability, and also a nasty issue with posting/putting payloads with null/undefined values.
- Added typings (and scripts to generate those) and added them to `src/references.d.ts` so our IDEs can leverage typing support for both `AFNetworking` and `okhttp3`.
- Added support for large responses. Default off (which is the current behavior). The problem was large responses would crash the app on Android with something like "network on main thread". This is caused by a strict policy, but it's actually a check that should only flag issues during development. It's active on release builds as well though so let's give plugin users a way to get around this.

### CODE REVIEW

**Comment by AresDev** [comment]
Great work @EddyVerbruggen, thank you! I'm also using this plugin and faced the same problems. I hope this PR could be merged soon.

**Comment by roblav96** [comment]
@EddyVerbruggen
My apologies for the late reply, I'll merge this in over the weekend!

**Comment by EddyVerbruggen** [comment]
No worries mate! Thanks for picking this up. Just know that if anything goes south after you release this I will fix it.

**Comment by EddyVerbruggen** [comment]
Hi guys,

I've added 2 more commits to the PR:
- Gradle wants us to use 'implementation' instead of 'compile' these days
- NativeScript 5.4 upgrade for the demo to show how to bundle a certificate with the new Webpack workflow (which will be standard for NativeScript 6).

If you have issues maintaining this awesome repo, please let me know and I'd be happy to help by merging and publishing this change myself. I'll take care of any issues that may come from it.

**Comment by roblav96** [comment]
Yes I agree, you'll be added to the repo

**Pull request merged**
